# Generated by Django 6.0 on 2026-02-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
