# Generated by Django 6.0 on 2026-03-02 19:20

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_post_viewed"),
    ]

    operations = [TrigramExtension()]
